#!/bin/bash
GOARCH=amd64
GOOS=linux
go build
GOOS=windows
go build
cp -r lifds-cp.ini lifds-cp.exe html ~/Dropbox/lifds-cp
go build -ldflags="-H windowsgui"
cp -r lifds-cp.ini lifds-cp.exe html ~/Dropbox/lifds-cp-bg
